# Generated by Django 3.0.3 on 2022-01-22 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220122_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='expected_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 6, 38, 16, 280336, tzinfo=utc)),
        ),
    ]
