# Generated by Django 3.0.3 on 2022-01-22 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220122_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='expected_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 7, 13, 27, 875862, tzinfo=utc)),
        ),
    ]
