# Generated by Django 3.0.3 on 2022-01-22 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220122_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='expected_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
