# Generated by Django 3.0.3 on 2022-01-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220122_0715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
